### ISSUE TITLE
Implementation of `PartialEq` for `Rc` and `Snapshot` should compare dereferenced value

### ISSUE THREAD

**Issue by powergee** [kaist-cp/circ#2]
Currently, the `PartialEq` implementation for `Rc` and `Snapshot` only compares between pointer values. However, `PartialEq`s for smart pointer types (e.g., [std::rc::Rc](https://doc.rust-lang.org/std/rc/struct.Rc.html#impl-PartialEq-for-Rc%3CT,+A%3E)) are often defined by actual objects they are pointing to.

It would be better to follow the standard convention and provide a separate `ptr_eq` for pointer comparison.

**Comment by simnalamburt** [comment]
Oh, it could have been a big problem if I had kept using it without knowing about this issue.
